/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package MANIFOLD.MINIMAL;

public class App {

    public void inc() {
    }

    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
	App a = new App();
//	a.inc();
	a++;
    }
}
